# -*- coding: utf-8 -*-
"""OPERADORES DE COMPARAÇÃO

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DCf1tCOyE6DaCAhbm9c8lWUQyhYI3kug
"""

X = 6 + 4 *2
print(X)

x = (4 * 9 +5)
print(x)

x = ((6 + 7)* 9)
print(x)

x = (15 + 20 - 30)
print (x)

x = (6 + 5 **2)
print (x)

x=8
print(x)
x+=5
print(x)
x-=4
print(x)
x*=20
print(x)
x/=2
print(x)

x=8
print(x)
x1=3
print(x1)
ct=x<x1
print(ct)
x_result=x==x1
print(x_result)
x_result=x>=x1
print(x_result)
x_result=x!=x1
print(x_result)